name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  cpy_3_10:
    name: CPython 3.10
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  pypy_3_10:
    name: PyPy 3.10
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  cpy_3_9:
    name: CPython 3.9
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  pypy_3_9:
    name: PyPy 3.9
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  cpy_3_8:
    name: CPython 3.8
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  pypy_3_8:
    name: PyPy 3.8
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  cpy_3_7:
    name: CPython 3.7
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  pypy_3_7:
    name: PyPy 3.7
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  cpy_3_6:
    name: CPython 3.6
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  pypy_3_6:
    name: PyPy 3.6
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  cpy_3_5:
    name: CPython 3.5
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: '3.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  pypy_3_5:
    name: PyPy 3.5
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: 'pypy3.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  cpy_2_7:
    name: CPython 2.7
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd==2.0.1

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -

  pypy_2_7:
    name: PyPy 2.7
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy2.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install test_cmd==2.0.1

      - name: Test Run
        run: |
          test_cmd tests `which python` pypage.py @ -
